# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('org.snmp4j', 'snmp4j', '2.8.4')
require_jar('org.snakeyaml', 'snakeyaml-engine', '2.7')
require_jar('org.logstash.integrations', 'logstash-integration-snmp', '4.0.0')
